[project]
name = "nexus"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Rishil Ramesh", email = "rishil.ramesh@outlook.com" }
]
requires-python = ">=3.13"
dependencies = [
    "langchain-openai>=1.6.2",
    "langgraph>=1.2.11",
    "pydantic-settings>=2.15.0",
    "streamlit>=1.63.0",
]

[project.scripts]
nexus = "nexus:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
